name: Lint
on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Check dependencies
        run: |
          go version
          test -z "$(go mod tidy  && git status --porcelain)"
          go mod verify

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run k6's golangci-lint CI
        uses: grafana/k6/.github/actions/lint@master

